language: node_js

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn install

matrix:
  include:
    - node_js: '8'
      name: Node.js 8
      before_script: yarn lint
      script: yarn test
    - node_js: '10'
      name: Node.js 10
      before_script: yarn lint
      script: yarn test
